theme: jekyll-theme-slate
title: F' - A Component Driven Flight Software Framework
description: F' is a framework for efficiently building component-based flight software and embedded solutions developed at Caltech/JPL.
